
DROP TABLE If EXISTS FILM;
DROP TABLE If EXISTS REALISATEUR;
DROP TABLE If EXISTS GENRE;


CREATE TABLE REALISATEUR (
    IdR INT PRIMARY KEY,
    Nom VARCHAR(20),
    Prenom VARCHAR(20)
);

CREATE TABLE GENRE (
    Nom VARCHAR(20) PRIMARY KEY,
    DescriptionG VARCHAR(255)
);

CREATE TABLE FILM (
    IdF INT PRIMARY KEY,
    Nom VARCHAR(20),
    synopsis VARCHAR(255),
    anneRealisation DATE,
    IdR INT REFERENCES REALISATEUR(IdR),
    genre VARCHAR(20) REFERENCES GENRE(nom)
)

